### ISSUE TITLE
Only jails myself

### ISSUE THREAD

**Issue by Ultrunz** [TanguyOrtegat/esx_jb_realtimejailer#1]
At the moment i can open the menu and ive copied in what you said including the line for the new policejob but it just jails myself

**Comment by TanguyOrtegat** [comment]
show me the whole code

**Comment by Ultrunz** [comment]
https://pastebin.com/ZifZJuNd

Line 890 starts the script. The rest is in the citizen menus

**Comment by TanguyOrtegat** [comment]
change closestplayer to closestPlayer

**Comment by Ultrunz** [comment]
Ok I will test after this class (just teaching.) Thanks :D

**Comment by TanguyOrtegat** [comment]
let me known if it works

**Comment by Ultrunz** [comment]
Works great! Love the script

**Comment by Ultrunz** [comment]
Is there a way to change it to minutes from hours?
