### ISSUE TITLE
Jailing myself

### ISSUE THREAD

**Issue by EGUltraTM** [TanguyOrtegat/esx_jb_realtimejailer#3]
Hi,

i insert the code and all also the menu to the police.

I also cant open the menu when no player is near which is ok.

But then i jail myself instead of the other player :D

**Comment by MoravianLion** [comment]
Are you sure you have correct value in policejob's client? 

 “openJailMenu(GetPlayerServerId(closestplayer))” (instead of "player")

**Comment by TanguyOrtegat** [comment]
indeed, check very good and pay attention, it is CaSeSeNsItIve
